# Use ubuntu base image
FROM ubuntu

# Be sure we're up to date
RUN apt-get update

# Get the essentials going
RUN apt-get install -y build-essential
RUN apt-get install -y git-core
RUN apt-get install -y curl
RUN apt-get install -y zlib1g-dev openssl libssl-dev libreadline-dev

# Get the ruby-build installed
RUN git clone https://github.com/sstephenson/ruby-build /tmp/ruby-build
RUN cd /tmp/ruby-build && ./install.sh

# Get Ruby installed
RUN ruby-build 2.1.0-preview1 /opt/ruby

# Update our environment
RUN echo '# Custom Ruby' > /etc/profile.d/ruby.sh
RUN echo 'export PATH=/opt/ruby/bin:$PATH' >> /etc/profile.d/ruby.sh
RUN chmod +x /etc/profile.d/ruby.sh
